[package]
name = "fast_record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magnus = "0.6"

[lib]
name = "fast_record"
crate-type = ["cdylib"]
